namespace SpriteKind {
    export const NPC = SpriteKind.create()
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Link_1,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    true
    )
    green_dir = 1
})
controller.player2.onButtonEvent(ControllerButton.Down, ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Link_2,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    500,
    false
    )
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Link_1,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    false
    )
    green_dir = 3
})
controller.player2.onButtonEvent(ControllerButton.Up, ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Link_2,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    500,
    false
    )
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Link_1,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    false
    )
    green_dir = 4
})
controller.player2.onButtonEvent(ControllerButton.Right, ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Link_2,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    500,
    false
    )
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Link_1,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    false
    )
    green_dir = 2
})
controller.player2.onButtonEvent(ControllerButton.Left, ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    Link_2,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    500,
    false
    )
})
controller.player1.onButtonEvent(ControllerButton.A, ControllerButtonEvent.Pressed, function () {
    if (green_dir == 4) {
        Attack = true
        animation.runImageAnimation(
        Link_1,
        [img`
            .....fffffff..........
            ....f6666666f.........
            ....f67777776f........
            ...f6777777776f.......
            ...f6777777777f.......
            ..f673555555636f......
            ..f675535555454f......
            .f63555f7555534f......
            .f6f5bbf3f55543fff....
            f66f5fdd4bf3bbf...f...
            f67f55fb4db13bf.ff.cc.
            f7fff5543dd18bf...ccc.
            .f...ffdddddddf..ccc..
            ......ffdddddf..ccc...
            ......ff6fffff88cc....
            ......f66f766f888.....
            ......f667766fb88.....
            ......fffddfffb.8.....
            ......f66bd66f........
            ......f666666f........
            ........feeff.........
            ........feeef.........
            .........fff..........
            `,img`
            .....fffffff..........
            ....f6666666f.........
            ....f67777776f........
            ...f6777777776f.......
            ...f6777777777f.......
            ..f673555555636f......
            ..f675535555454f......
            .f63555f7555534f......
            .f6f5bbf3f55543f......
            f66f5fdd4bf3bbf.......
            f67f55fb4db13bf.......
            f7fff5543dd18bf.......
            .f...ffdddddddf.......
            ......ffdddddf......f.
            ......ff6fffff88..f..f
            ......f66f766f888..f.f
            ......f667766fb8cccccc
            ......fffddfffb8cccccc
            ......f66bd66f888.....
            ......f666666f88......
            ........feeff.........
            ........feeef.........
            .........fff..........
            `,img`
            .....fffffff..........
            ....f6666666f.........
            ....f67777776f........
            ...f6777777776f.......
            ...f6777777777f.......
            ..f673555555636f......
            ..f675535555454f......
            .f63555f7555534f......
            .f6f5bbf3f55543f......
            f66f5fdd4bf3bbf.......
            f67f55fb4db13bf.......
            f7fff5543dd18bf.......
            .f...ffdddddddf.......
            ......ffdddddf........
            ......ff6fffff........
            ......f66f766f........
            ......f667766fb..8....
            ......fffddfffb888....
            ......f66bd66f88c..f.f
            ......f666666f8cccf..f
            ........feeff88.ccc.f.
            ........feeef....ccc..
            .........fff......cc..
            `,img`
            .....fffffff..........
            ....f6666666f.........
            ....f67777776f........
            ...f6777777776f.......
            ...f6777777777f.......
            ..f673555555636f......
            ..f675535555454f......
            .f63555f7555534f......
            .f6f5bbf3f55543f......
            f66f5fdd4bf3bbf.......
            f67f55fb4db13bf.......
            f7fff5543dd18bf.......
            .f...ffdddddddf.......
            ......ffdddddf........
            ......ff6fffff........
            ......f66f766f........
            ......f667766f........
            ......fffddfff........
            ......f66bd66f........
            ......f666666f........
            ........feeff.........
            ........feeef.........
            .........fff..........
            `],
        100,
        false
        )
        Attack = false
    }
    if (green_dir == 3) {
        Attack = true
        animation.runImageAnimation(
        Link_1,
        [img`
            ..........fffffff.....
            .........f6666666f....
            ........f67777776f....
            .......f6777777776f...
            .......f7777777776f...
            ......f636555555376f..
            ......f454555535576f..
            ......f4355557f55536f.
            ....fff34555f3fbb5f6f.
            ...f...fbb3fb4ddf5f66f
            .cc.ff.fb31bd4bf55f76f
            .ccc...fb81dd3455fff7f
            ..ccc..fdddddddff...f.
            ...ccc..fdddddff......
            ....cc88fffff6ff......
            .....88bf667f66f......
            .....8bdf667766f......
            .....8..fffddfff......
            ........f66db66f......
            ........f666666f......
            .........ffeef........
            .........feeef........
            ..........fff.........
            `,img`
            ..........fffffff.....
            .........f6666666f....
            ........f67777776f....
            .......f6777777776f...
            .......f7777777776f...
            ......f636555555376f..
            ......f454555535576f..
            ......f4355557f55536f.
            ......f34555f3fbb5f6f.
            .......fbb3fb4ddf5f66f
            .......fb31bd4bf55f76f
            .......fb81dd3455fff7f
            .......fdddddddff...f.
            ........fdddddff......
            ......88fffff6ff......
            .....888f667f66f......
            cccccc8bf667766f......
            cccccc8bfffddfff......
            f.f..888f66db66f......
            f..f..88f666666f......
            .f.......ffeef........
            .........feeef........
            ..........fff.........
            `,img`
            ..........fffffff.....
            .........f6666666f....
            ........f67777776f....
            .......f6777777776f...
            .......f7777777776f...
            ......f636555555376f..
            ......f454555535576f..
            ......f4355557f55536f.
            ......f34555f3fbb5f6f.
            .......fbb3fb4ddf5f66f
            .......fb31bd4bf55f76f
            .......fb81dd3455fff7f
            .......fdddddddff...f.
            ........fdddddff......
            ........fffff6ff......
            ........f667f66f......
            ....8...f667766f......
            ....88dbfffddfff......
            f.f..88df66db66f......
            f..fcc88f666666f......
            .f.ccc.88ffeef........
            ..ccc....feeef........
            ..cc......fff.........
            `,img`
            ..........fffffff.....
            .........f6666666f....
            ........f67777776f....
            .......f6777777776f...
            .......f7777777776f...
            ......f636555555376f..
            ......f454555535576f..
            ......f4355557f55536f.
            ......f34555f3fbb5f6f.
            .......fbb3fb4ddf5f66f
            .......fb31bd4bf55f76f
            .......fb81dd3455fff7f
            .......fdddddddff...f.
            ........fdddddff......
            ........fffff6ff......
            ........f667f66f......
            ........f667766f......
            ........fffddfff......
            ........f66db66f......
            ........f666666f......
            .........ffeef........
            .........feeef........
            ..........fff.........
            `],
        100,
        false
        )
        Attack = false
    }
    if (green_dir == 2) {
        Attack = true
        animation.runImageAnimation(
        Link_1,
        [img`
            ......ffffff......
            .....f677776f.....
            ....f67777776f....
            ...f6777777776f...
            ...f7355535537f...
            ..f635555555536f..
            bbff4545555355ffbb
            fdd64355553b353ddf
            .fbf34555fbd343bf.
            ..f5f443fbdddf5f..
            ..f54f3bbdd3335f..
            ..f5f183dd381f4f..
            ..fff181dd181ff...
            ....fbdddddddf....
            ...f7ffbbbbff7f...
            ..f776666666677f..
            .fddff666666ff87f.
            .fbd67ff11fddb88f.
            ..fff676116dd88f..
            ....ff67778888cf.f
            ...feefffff88ccc.f
            ...feeef..feeecccf
            ....fff....ffffccc
            ................cc
            ..................
            `,img`
            ......ffffff......
            .....f677776f.....
            ....f67777776f....
            ...f6777777776f...
            ...f7355535537f...
            ..f635555555536f..
            bbff4545555355ffbb
            fdd64355553b353ddf
            .fbf34555fbd343bf.
            ..f5f443fbdddf5f..
            ..f54f3bbdd3335f..
            ..f5f183dd381f4f..
            ..fff181dd181ff...
            ....fbdddddddf....
            ...f7ffbbbbff7f...
            ..f77666666667f...
            .fddff77777f77f...
            .fb666686ff777f...
            ..fff188fdb77f6f..
            ...f61888db7f66f..
            ..f677cc88ccf666f.
            ..feeccc888efeef..
            ..ffccc..cccffff..
            ...ccc............
            ...cc...ccccc.....
            `,img`
            ......ffffff......
            .....f677776f.....
            ....f67777776f....
            ...f6777777776f...
            ...f7355535537f...
            ..f635555555536f..
            bbff4545555355ffbb
            fdd64355553b353ddf
            .fbf34555fbd343bf.
            ..f5f443fbdddf5f..
            ..f54f3bbdd3335f..
            ..f5f183dd381f4f..
            ..fff181dd181ff...
            ....fbdddddddf....
            ...f7ffbbbbff7f...
            ..f776666666677f..
            .fddff666666ffddf.
            .fbd67ff11ff76dbf.
            ..fff67611676fff..
            ....ff677776ff....
            ...feeffffffeef...
            ...feeef..feeef...
            ....fff....fff....
            ..................
            ..................
            `],
        150,
        false
        )
        Attack = false
    }
    if (green_dir == 1) {
        Attack = true
        animation.runImageAnimation(
        Link_1,
        [img`
            ......ffffff...........
            .....f677776f..........
            ....f67777776f.........
            ...f6777777776f........
            ...f7777777776f........
            ..f677777777776f.......
            bbff77777777776fbb.....
            fddf77777777776ddf.....
            .fbff7777777776bf....cc
            ..f5f777777776ff....ccc
            ..f54ffff77776f....cccf
            ..f5f3455f7776f.88ccc.f
            ..ffff3444fffff888ccf.f
            ....fbffffdddf..8888f.f
            ...f7ffbbbbff7ffff88.f.
            ..f776666666677fddf8...
            .fddff666666ff77fdf....
            .fbd67ffffff76777f.....
            ..fff67666676ff77f.....
            ....ff677776ff.ff......
            ...feeffffffeef........
            ...feeef..feeef........
            ....fff....fff.........
            `,img`
            ......ffffff...........
            .....f677776f..........
            ....f67777776f.........
            ...f6777777776f........
            ...f7777777776f........
            ..f677777777776f.......
            bbff77777777776fbb.....
            fddf77777777776ddf.....
            .fbff7777777776bf......
            ..f5f777777776ff.......
            ..f54ffff77776f........
            ..f5f3455f7776f88......
            ..ffff3444fffff888.....
            ....fbffffdddf8ff......
            ...f7ffbbbbff7fdf......
            ..f776666666677ff......
            .fddff666666ff7f.......
            .fbd67ffffff76ff.......
            ..fff67666676ff........
            ....ff677776ff.........
            ...feeffffffeef........
            ...feeef..feeef........
            ....fff....fff.........
            `,img`
            ......ffffff...........
            .....f677776f..........
            ....f67777776f.........
            ...f6777777776f........
            ...f7777777776f........
            ..f677777777776f.......
            bbff77777777776fbb.....
            fddf77777777776ddf.....
            .fbff7777777776bf......
            ..f5f777777776ff.......
            ..f54ffff77776f........
            ..f5f3455f7776f........
            ..ffff3444fffff........
            ....fbffffdddf.........
            ...f7ffbbbbff7f........
            ..f776666666677f.......
            .fddff666666ffddf......
            .fbd67ffffff76dbf......
            ..fff67666676fff.......
            ....ff677776ff.........
            ...feeffffffeef........
            ...feeef..feeef........
            ....fff....fff.........
            `],
        150,
        false
        )
        Attack = false
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`transparency16`, function (sprite, location) {
    tiles.setCurrentTilemap(tilemap`level2`)
})
let Attack = false
let green_dir = 0
let Link_2: Sprite = null
let Link_1: Sprite = null
Link_1 = sprites.create(assets.image`Link 1`, SpriteKind.Player)
Link_2 = sprites.create(assets.image`Link 2`, SpriteKind.Player)
controller.moveSprite(Link_1)
controller.player2.moveSprite(Link_2, 100, 100)
splitScreen.cameraFollowSprite(splitScreen.Camera.Camera1, Link_1)
splitScreen.cameraFollowSprite(splitScreen.Camera.Camera2, Link_2)
tiles.setCurrentTilemap(tilemap`level1`)
tiles.placeOnRandomTile(Link_1, assets.tile`transparency16`)
tiles.placeOnRandomTile(Link_2, assets.tile`transparency16`)
let Old_man = sprites.create(img`
    . . . . . c c c c c c . . . . . 
    . . . . c c c c c c c c . . . . 
    . . . c c c c c c . c c . . . . 
    . . . b b b c c c c . . . . . . 
    . . d d b b b c c c . . . . . . 
    . . . 1 d b b c c c c . . . . . 
    . . . 1 1 1 1 c c c c . . . . . 
    . . . 1 1 1 8 8 8 c c . . . . . 
    . . . d d 8 8 8 8 c c . . . . . 
    . . . d d 8 8 c c c c c . . . . 
    . . . e 1 1 c c c c c c . . . . 
    . . . e . 1 c c c c c c . . . . 
    . . . e . c c c c c c c c . . . 
    . . . e . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    `, SpriteKind.NPC)
tiles.placeOnRandomTile(Old_man, assets.tile`transparency16`)
Old_man.setScale(1.75, ScaleAnchor.Middle)
forever(function () {
    info.changeScoreBy(1)
})
